FROM python:3.11-slim

RUN pip install --no-cache-dir uv

WORKDIR /app

COPY pyproject.toml .
COPY src/ src/
RUN echo "# LLM Framework" > README.md

RUN uv pip install --system  .[celery,core,db,adapters,api]

CMD ["celery", "-A", "src.core.tasks.celery_app", "worker", "--loglevel=info"]